public enum PlayerStatus
{
    NONE, CHALLENGE, PHOTON_LOBBY, LOBBY_ROOM,
    RANDOM_JOIN, RANDOM_JOIN_FAILED, PHOTON_LOBBY_FAILED,
    LEAVE_ROOM, OPPONENT_JOINED, OPPONENT_LEFT,
    JOIN_CHALLENGE, CREATE_CHALLENGE, JOIN_CHALLENGE_FAILED,
    CREATE_ROOM_FAILED,
    IN_GAME,
    SHUFFLED,
    RANDOM_JOIN_RECONNECT,
    RELOAD_SCENE,
    ON_MASTER_CLENT_SWITCH,
    TOURNEMENT_MATCH
}